# Generated by Django 4.2.7 on 2023-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='dloc',
            field=models.CharField(default='india', max_length=100),
        ),
    ]
